## Sprint 2 Preparacion y Limpieza de encuesta
### Carga de datos del formulario

In [18]:
# importar librerias necesarias para carga de datas
import pandas as pd

In [19]:
# Almacenar en una variable
df = pd.read_csv("../datas/Formulario movilidad estudiantil y rendimiento académico.csv")
df.head(10)

,Marca temporal,Nombre completo,Correo electrónico institucional,Programa académico al que pertenece,Semestre actual que esta cursando,Jornada recurrente de clases o asistencia a la universidad,Lugar de residencia,Principal medio de transporte utilizado para la universidad,¿Cuánto tiempo en promedio tarda en llegar a la universidad?,¿Cuánto tiempo en promedio tarda en regresar de la universidad a su lugar de residencia?,...,¿El tiempo de desplazamiento es variado? (escala de 1 a 5),¿Cuántas veces a la semana tiene que asistir a clases presenciales?,¿Cuántas veces llega tarde a clases en la semana debido al transporte?,¿Cuántas clases a la semana pierde por problemas de movilidad?,¿Cuál es tu promedio académico actual?,¿Considera qué el tiempo de desplazamiento afecta tu rendimiento y puntualidad?,¿Cuántas horas al día dedica a estudiar y hacer tareas?,¿Considera qué pierde tiempo para estudiar debido a la movilidad que realizar diariamente?,¿Qué actividad realiza durante los desplazamientos?,¿Aceptaría cambiar el horario si esto redujera el tiempo de desplazamientos?
0,2026/05/06 7:00:56 p. m. GMT-5,Juan David,Jecheverria@ucundinamarca.edu.co,Ingeniería de software,"7, 8 semestre",Mañana y tarde,Soacha (central),"Bicicleta, mono patin, patineta, etc.",Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,2 (Estable),5 días,1 o 2 veces,No pierdo clases,4.1 a 4.5,A veces,3 a 4 horas,Sí,Nada,Tal vez
1,2026/05/06 7:47:55 p. m. GMT-5,Juan Camilo Gomez Lopez,jcgomezlopez@ucundinamarca.edu.co,Ingeniería de software,"7, 8 semestre",Mañana y tarde,Soacha (al rededores),"Bicicleta, mono patin, patineta, etc.",Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,3 (Depende del día y del horario ),4 días,3 o 4 veces,1 clase,4.1 a 4.5,Sí,3 a 4 horas,Sí,Escuchar música o podcast,Sí
2,2026/05/06 8:53:41 p. m. GMT-5,Julian Felipe Flórez Ortiz,jfelipeflorez@ucundinamarca.edu.co,Ingeniería de software,"7, 8 semestre",Mañana y tarde,Soacha (central),Bus,30 a 60 minutos (media a una hora),30 a 60 minutos (media a una hora),...,3 (Depende del día y del horario ),4 días,1 o 2 veces,1 clase,4.1 a 4.5,Sí,3 a 4 horas,A veces,Escuchar música o podcast,Sí
3,2026/05/07 5:20:21 p. m. GMT-5,Zharick Natalia Mendoza Fonseca,znmendoza@ucundinamarca.edu.co,Ciencias del deporte,"7, 8 semestre",Mañana y tarde,Soacha (al rededores),"Bicicleta, mono patin, patineta, etc.",Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,3 (Depende del día y del horario ),5 días,Ninguna,No pierdo clases,3.6 a 4.0,Sí,3 a 4 horas,Sí,Escuchar música o podcast,Sí
4,2026/05/07 5:23:42 p. m. GMT-5,Paula Mendoza Fonseca,pvmendoza@ucundinamarca.edu.co,Ingeniería de software,"1, 2 semestre",Mañana únicamente,Soacha (al rededores),Bus,Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,3 (Depende del día y del horario ),4 días,Ninguna,No pierdo clases,4.1 a 4.5,A veces,3 a 4 horas,No,Escuchar música o podcast,Tal vez
5,2026/05/07 5:24:36 p. m. GMT-5,Irma Fonseca Sáenz,irmafon.04@hotmail.com,Administración de empresas,"3, 4 semestre",Noche,Soacha (al rededores),Bus,30 a 60 minutos (media a una hora),30 a 60 minutos (media a una hora),...,3 (Depende del día y del horario ),4 días,1 o 2 veces,No pierdo clases,4.1 a 4.5,A veces,3 a 4 horas,A veces,Escuchar música o podcast,Sí
6,2026/05/07 6:25:15 p. m. GMT-5,Sergio Suárez Villarraga,sergiosuarez@ucundinamarca.edu.co,Ciencias del deporte,"5, 6 semestre",Mañana y tarde,Soacha (central),Caminando,Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,2 (Estable),5 días,Ninguna,1 clase,3.6 a 4.0,Sí,3 a 4 horas,A veces,Escuchar música o podcast,Tal vez
7,2026/05/07 7:24:33 p. m. GMT-5,Jenifer Vivian Chavarro Vera,jvchavarro@ucundinamarca.edu.co,Ciencias del deporte,9 o superior,Mañana y tarde,Soacha (central),Bus,Menos de 30 minutos (media hora o menos),Menos de 30 minutos (media hora o menos),...,3 (Depende del día y del horario ),5 días,1 o 2 veces,No pierdo clases,4.1 a 4.5,A veces,3 a 4 horas,No,Escuchar música o podcast,Tal vez
8,2026/05/11 1:22:55 p. m. GMT-5,esteban sanchez caicedo,esanchezc@ucundinamarca.edu.co,Ingeniería de software,"7, 8 semestre",Mañana y tarde,Bogotá (norte),"Transmilenio (Buses troncales, SITP, alimentador)",Más de 2 horas,Más de 2 horas,...,5 (Es muy variado),5 días,5 o más veces,2 clases,3.6 a 4.0,Sí,3 a 4 horas,Sí,Escuchar música o podcast,Tal vez
9,2026/05/11 1:24:41 p. m. GMT-5,Juan Sebastian Latorre Rojas,jslatorre@ucundinamarca.edu.co,Administración de empresas,"3, 4 semestre",Noche,Bogotá (sur),Bus,61 a 90 minutos (una hora a hora y media),61 a 90 minutos (una hora a hora y media),...,4 (Varia algo),4 días,1 o 2 veces,No pierdo clases,4.1 a 4.5,Sí,5 o más horas,Sí,Escuchar música o podcast,Tal vez

In [31]:
# Ver informacion general para conocer columnas y que datos podemos usar
df.info() # ver informacion sobre las columnas que necesitamos y al tipo que debemos convertir

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   programa                    50 non-null     string
 1   grupo_semestre              50 non-null     int64
 2   jornada                     50 non-null     string
 3   residencia                  50 non-null     string
 4   medio_transporte            50 non-null     string
 5   tiempo_llegada              50 non-null     string
 6   tiempo_regreso              50 non-null     string
 7   trasbordos                  50 non-null     int64
 8   hora_desplazamiento         50 non-null     string
 9   tiempo_desplazamiento       50 non-null     int64
 10  dias_asistencia             50 non-null     int64
 11  llegadas_tarde              50 non-null     float64
 12  pierde_clase                50 non-null     int64
 13  promedio_academico          50 non-null     string
 14  afecta_rendimiento          50 non-null     string
 15  horas_estudiar              50 non-null     float64
 16  pierde_tiempo               50 non-null     string
 17  actividades_desplazamiento  50 non-null     string
 18  cambia_horario              50 non-null     string
dtypes: float64(2), int64(5), string(12)
memory usage: 7.6 KB

## Limpieza de Dataset

In [21]:
# importe de librerias necesarias
import unicodedata

In [22]:
# 1. Eliminar columnas innecesarias almacenar en una lista y luego hacer drop
columnas_a_eliminar = [
    'Marca temporal', 
    'Nombre completo', 
    'Correo electrónico institucional '
]
df = df.drop(columns=columnas_a_eliminar)

In [ ]:
# 2. Funcion para limpiar texto: minusculas, sin tildes, sin espacios extra (se llama mas adelante)
# funcion para limpiar los textos, convertir a minusculas y quitar tildes
def limpiar_texto(texto):
    if pd.isna(texto):
        return texto
    texto = str(texto).lower().strip()
    # Normalizar para quitar tildes
    texto = unicodedata.normalize('NFKD', texto).encode('ASCII', 'ignore').decode('utf-8')
    return texto

In [24]:
# 3. Renombrar las columnas para facilitar su manejo
nuevos_nombres = {
    'Programa académico al que pertenece': 'programa',
    'Semestre actual que esta cursando': 'grupo_semestre', # pasara a ser un grupo_semestre
    'Jornada recurrente de clases o asistencia a la universidad': 'jornada',
    'Lugar de residencia': 'residencia',
    'Principal medio de transporte utilizado para la universidad': 'medio_transporte',
    '¿Cuánto tiempo en promedio tarda en llegar a la universidad?': 'tiempo_llegada',
    '¿Cuánto tiempo en promedio tarda en regresar de la universidad a  su lugar de residencia? ': 'tiempo_regreso',
    'Realizas trasbordos en tu trayecto (cambios de transporte a lo largo del trayecto)': 'trasbordos',
    '¿En qué tipo de horario realiza la mayor parte del desplazamiento?': 'hora_desplazamiento',
    '¿El tiempo de desplazamiento es variado? (escala de 1 a 5)': 'tiempo_desplazamiento',
    '¿Cuántas veces a la semana tiene que asistir a clases presenciales?': 'dias_asistencia',
    '¿Cuántas veces llega tarde a clases en la semana debido al transporte?': 'llegadas_tarde',
    '¿Cuántas clases a la semana pierde por problemas de movilidad?': 'pierde_clase',
    '¿Cuál es tu promedio académico actual?': 'promedio_academico',
    '¿Considera qué el tiempo de desplazamiento afecta tu rendimiento y puntualidad?': 'afecta_rendimiento',
    '¿Cuántas horas al día dedica a estudiar y hacer tareas?': 'horas_estudiar',
    '¿Considera qué pierde tiempo para estudiar debido a la movilidad que realizar diariamente?': 'pierde_tiempo',
    '¿Qué actividad realiza durante los desplazamientos?': 'actividades_desplazamiento',
    '¿Aceptaría cambiar el horario si esto redujera el tiempo de desplazamientos?': 'cambia_horario'
}
df = df.rename(columns=nuevos_nombres)

# Aplicar limpieza de texto a todas las columnas de tipo objeto (cadenas)
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].apply(limpiar_texto) # llamar la funcion para limpiar textos

In [ ]:
# 4. Transformaciones y agrupaciones mas especificas

# Grupo de semestres a valores numéricos (1 al 5) donde 1 es semestres 1 y 2 y 9 es semestre 9
mapeo_semestres = {
    '1, 2 semestre': 1,
    '3, 4 semestre': 2,
    '5, 6 semestre': 3,
    '7, 8 semestre': 4,
    '9 o superior': 5
}
df['grupo_semestre'] = df['grupo_semestre'].map(mapeo_semestres)

# Hora de desplazamiento
mapeo_desplazamiento = {
    'ambos': "ambos",
    'horas valle (poca congestion vehicular y de personas)': "valle",
    'horas pico (mucha congestion vehicular y de personas)': "pico" 
}
df['hora_desplazamiento'] = df['hora_desplazamiento'].map(mapeo_desplazamiento)

# Trasbordos
mapeo_trasbordos = {
    'ninguno': 0,
    '1': 1,
    '2': 2,
    'mas de 3': 3 # Agrupamos 3 o mas como 3 (numérico)
}
df['trasbordos'] = df['trasbordos'].map(mapeo_trasbordos)

# Tiempos de desplazamiento (Llegada y Regreso) -> Mantenidos como cadenas limpias para agrupar
mapeo_tiempos_grupos = {
    'menos de 30 minutos (media hora o menos)': '0-30 min',
    '30 a 60 minutos (media a una hora)': '30-60 min',
    '61 a 90 minutos (una hora a hora y media)': '61-90 min',
    '91 a 120 minutos (hora y media a dos horas)': '91-120 min',
    'mas de 2 horas': 'Mas de 120 min'
}
df['tiempo_llegada'] = df['tiempo_llegada'].map(mapeo_tiempos_grupos)
df['tiempo_regreso'] = df['tiempo_regreso'].map(mapeo_tiempos_grupos)

# Extraer el valor numerico (1 a 5) de la escala de variabilidad
df['tiempo_desplazamiento'] = df['tiempo_desplazamiento'].str.extract(r'(\d+)').astype(int)

# Días de asistencia a presencial (ej: '5 dias' -> 5)
df['dias_asistencia'] = df['dias_asistencia'].str.extract(r'(\d+)').astype(int)

# Llegadas tarde semanales -> Escala ordinal/numerica
mapeo_tardes = {
    'ninguna': 0,
    '1 o 2 veces': 1.5,
    '3 o 4 veces': 3.5,
    '5 o mas veces': 5
}
df['llegadas_tarde'] = df['llegadas_tarde'].map(mapeo_tardes)

# Clases perdidas semanales -> Escala ordinal/numerica
mapeo_pierde = {
    'no pierdo clases': 0,
    '1 clase': 1,
    '2 clases': 2,
    '3 clases': 3,
    '4 o mas clases': 4
}
df['pierde_clase'] = df['pierde_clase'].map(mapeo_pierde)

# Horas dedicadas a estudiar -> Escala numerica (punto medio en horas)
mapeo_estudio = {
    'menos de 2 horas': 1,
    '3 a 4 horas': 3.5,
    '5 o mas horas': 5.5
}
df['horas_estudiar'] = df['horas_estudiar'].map(mapeo_estudio)

In [ ]:
# 6. Forzar tipos de datos finales

# Agregamos 'tiempo_llegada' y 'tiempo_regreso' a las categoricas
columnas_categoricas = [
    'programa', 'jornada', 'residencia', 'medio_transporte', 
    'tiempo_llegada', 'tiempo_regreso', 'hora_desplazamiento', 
    'afecta_rendimiento', 'pierde_tiempo', 'actividades_desplazamiento', 
    'cambia_horario', 'promedio_academico'
]
df[columnas_categoricas] = df[columnas_categoricas].astype("string")

# Quitamos las de tiempo de la lista numerica
columnas_numericas = [
    'grupo_semestre', 'trasbordos', 'tiempo_desplazamiento', 'dias_asistencia', 
    'llegadas_tarde', 'pierde_clase', 'horas_estudiar'
]

for col in columnas_numericas:
    df[col] = pd.to_numeric(df[col], errors='coerce')

# Verificacion
print(df[['tiempo_llegada', 'tiempo_regreso']].head())

  tiempo_llegada tiempo_regreso
0       0-30 min       0-30 min
1       0-30 min       0-30 min
2      30-60 min      30-60 min
3       0-30 min       0-30 min
4       0-30 min       0-30 min

### Verificamos que los datos esten correctos y listos para analisis

In [27]:
print(df.describe())

       grupo_semestre  trasbordos  tiempo_desplazamiento  dias_asistencia  \
count       50.000000   50.000000              50.000000        50.000000
mean         2.540000    0.280000               3.060000         4.520000
std          1.215713    0.572855               0.956396         0.646498
min          1.000000    0.000000               1.000000         3.000000
25%          2.000000    0.000000               2.250000         4.000000
50%          2.000000    0.000000               3.000000         4.000000
75%          4.000000    0.000000               3.000000         5.000000
max          5.000000    2.000000               5.000000         6.000000

       llegadas_tarde  pierde_clase  horas_estudiar
count       50.000000     50.000000       50.000000
mean         1.570000      0.600000        3.510000
std          1.474304      0.880631        1.275715
min          0.000000      0.000000        1.000000
25%          0.000000      0.000000        3.500000
50%          1.500000      0.000000        3.500000
75%          1.500000      1.000000        3.500000
max          5.000000      4.000000        5.500000

In [28]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 19 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   programa                    50 non-null     string
 1   grupo_semestre              50 non-null     int64
 2   jornada                     50 non-null     string
 3   residencia                  50 non-null     string
 4   medio_transporte            50 non-null     string
 5   tiempo_llegada              50 non-null     string
 6   tiempo_regreso              50 non-null     string
 7   trasbordos                  50 non-null     int64
 8   hora_desplazamiento         50 non-null     string
 9   tiempo_desplazamiento       50 non-null     int64
 10  dias_asistencia             50 non-null     int64
 11  llegadas_tarde              50 non-null     float64
 12  pierde_clase                50 non-null     int64
 13  promedio_academico          50 non-null     string
 14  afecta_rendimiento          50 non-null     string
 15  horas_estudiar              50 non-null     float64
 16  pierde_tiempo               50 non-null     string
 17  actividades_desplazamiento  50 non-null     string
 18  cambia_horario              50 non-null     string
dtypes: float64(2), int64(5), string(12)
memory usage: 7.6 KB
None

In [29]:
df.head(50)

,programa,grupo_semestre,jornada,residencia,medio_transporte,tiempo_llegada,tiempo_regreso,trasbordos,hora_desplazamiento,tiempo_desplazamiento,dias_asistencia,llegadas_tarde,pierde_clase,promedio_academico,afecta_rendimiento,horas_estudiar,pierde_tiempo,actividades_desplazamiento,cambia_horario
0,ingenieria de software,4,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,ambos,2,5,1.5,0,4.1 a 4.5,a veces,3.5,si,nada,tal vez
1,ingenieria de software,4,manana y tarde,soacha (al rededores),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,ambos,3,4,3.5,1,4.1 a 4.5,si,3.5,si,escuchar musica o podcast,si
2,ingenieria de software,4,manana y tarde,soacha (central),bus,30-60 min,30-60 min,0,ambos,3,4,1.5,1,4.1 a 4.5,si,3.5,a veces,escuchar musica o podcast,si
3,ciencias del deporte,4,manana y tarde,soacha (al rededores),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,ambos,3,5,0.0,0,3.6 a 4.0,si,3.5,si,escuchar musica o podcast,si
4,ingenieria de software,1,manana unicamente,soacha (al rededores),bus,0-30 min,0-30 min,0,valle,3,4,0.0,0,4.1 a 4.5,a veces,3.5,no,escuchar musica o podcast,tal vez
5,administracion de empresas,2,noche,soacha (al rededores),bus,30-60 min,30-60 min,0,ambos,3,4,1.5,0,4.1 a 4.5,a veces,3.5,a veces,escuchar musica o podcast,si
6,ciencias del deporte,3,manana y tarde,soacha (central),caminando,0-30 min,0-30 min,0,ambos,2,5,0.0,1,3.6 a 4.0,si,3.5,a veces,escuchar musica o podcast,tal vez
7,ciencias del deporte,5,manana y tarde,soacha (central),bus,0-30 min,0-30 min,0,valle,3,5,1.5,0,4.1 a 4.5,a veces,3.5,no,escuchar musica o podcast,tal vez
8,ingenieria de software,4,manana y tarde,bogota (norte),"transmilenio (buses troncales, sitp, alimentador)",Mas de 120 min,Mas de 120 min,2,pico,5,5,5.0,2,3.6 a 4.0,si,3.5,si,escuchar musica o podcast,tal vez
9,administracion de empresas,2,noche,bogota (sur),bus,61-90 min,61-90 min,1,pico,4,4,1.5,0,4.1 a 4.5,si,5.5,si,escuchar musica o podcast,tal vez
10,ingenieria industrial,2,manana y tarde,bogota (sur),bus,61-90 min,61-90 min,1,pico,2,4,0.0,0,4.1 a 4.5,a veces,5.5,si,nada,si
11,ingenieria de software,2,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",30-60 min,0-30 min,0,ambos,3,5,0.0,0,4.1 a 4.5,a veces,1.0,no,escuchar musica o podcast,si
12,ingenieria industrial,2,manana y tarde,soacha (al rededores),bus,30-60 min,30-60 min,1,pico,3,4,1.5,0,4.1 a 4.5,si,3.5,si,escuchar musica o podcast,si
13,ingenieria de software,2,manana y tarde,bogota (sur),bus,30-60 min,30-60 min,0,ambos,5,6,3.5,0,4.1 a 4.5,si,5.5,si,escuchar musica o podcast,si
14,ingenieria de software,1,manana y tarde,soacha (al rededores),bus,0-30 min,30-60 min,0,ambos,3,4,0.0,0,4.1 a 4.5,no,3.5,no,escuchar musica o podcast,si
15,ingenieria de software,1,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,pico,2,4,0.0,2,3.0 a 3.5,a veces,3.5,si,nada,si
16,ingenieria de software,1,manana y tarde,bogota (sur),bus,30-60 min,61-90 min,1,ambos,3,5,1.5,0,4.1 a 4.5,si,3.5,si,escuchar musica o podcast,no
17,ingenieria de software,1,manana unicamente,soacha (al rededores),bus,30-60 min,30-60 min,0,pico,4,4,1.5,0,4.1 a 4.5,si,5.5,si,escuchar musica o podcast,no
18,ingenieria de software,2,manana unicamente,bogota (sur),moto (combustion o electrica),0-30 min,0-30 min,0,pico,5,5,1.5,2,3.6 a 4.0,a veces,5.5,a veces,nada,tal vez
19,ingenieria de software,2,manana y tarde,soacha (al rededores),bus,91-120 min,61-90 min,0,pico,3,5,1.5,1,4.1 a 4.5,a veces,3.5,si,descansar o dormir,si
20,ingenieria de software,3,manana y tarde,soacha (central),moto (combustion o electrica),0-30 min,0-30 min,0,valle,2,5,1.5,0,4.1 a 4.5,a veces,1.0,no,nada,si
21,ingenieria de software,2,manana y tarde,bogota (sur),bus,61-90 min,91-120 min,2,ambos,3,4,1.5,1,4.1 a 4.5,si,3.5,si,descansar o dormir,tal vez
22,ingenieria industrial,2,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,valle,2,4,0.0,0,3.6 a 4.0,no,1.0,no,escuchar musica o podcast,no
23,ingenieria de software,4,manana y tarde,soacha (central),"transmilenio (buses troncales, sitp, alimentador)",61-90 min,91-120 min,0,pico,1,6,1.5,1,3.6 a 4.0,no,3.5,a veces,descansar o dormir,no
24,ingenieria de software,4,manana y tarde,mosquera,bus,61-90 min,61-90 min,1,pico,2,5,3.5,1,3.6 a 4.0,si,3.5,si,descansar o dormir,si
25,ingenieria de software,2,manana y tarde,sibate,bus,61-90 min,61-90 min,1,pico,4,4,1.5,1,4.1 a 4.5,si,3.5,si,escuchar musica o podcast,tal vez
26,ingenieria de software,4,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,valle,2,4,0.0,0,4.1 a 4.5,no,5.5,no,nada,tal vez
27,ingenieria de software,4,manana y tarde,soacha (central),bus,61-90 min,61-90 min,0,pico,3,4,5.0,3,4.1 a 4.5,si,3.5,si,escuchar musica o podcast,tal vez
28,ingenieria de software,4,manana y tarde,bogota (sur),bus,30-60 min,30-60 min,0,valle,2,5,5.0,1,4.1 a 4.5,si,1.0,si,escuchar musica o podcast,si
29,ingenieria de software,2,manana y tarde,soacha (al rededores),caminando,0-30 min,0-30 min,0,pico,2,4,0.0,0,3.0 a 3.5,si,3.5,si,escuchar musica o podcast,si
30,ingenieria industrial,4,manana y tarde,bogota (sur),bus,0-30 min,0-30 min,0,ambos,3,4,1.5,0,4.1 a 4.5,a veces,3.5,a veces,descansar o dormir,si
31,ingenieria de software,4,manana y tarde,soacha (central),caminando,0-30 min,0-30 min,0,ambos,3,5,0.0,0,4.1 a 4.5,a veces,3.5,a veces,estudiar o leer,si
32,ingenieria de software,2,manana y tarde,bogota (sur),bus,61-90 min,61-90 min,1,pico,4,5,3.5,0,3.6 a 4.0,a veces,3.5,a veces,descansar o dormir,tal vez
33,ingenieria de software,2,manana y tarde,soacha (al rededores),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,ambos,3,4,0.0,0,4.6 a 5,a veces,3.5,a veces,escuchar musica o podcast,tal vez
34,ingenieria de software,4,manana y tarde,bogota (sur),bus,30-60 min,30-60 min,0,pico,3,5,1.5,2,3.6 a 4.0,si,3.5,si,escuchar musica o podcast,si
35,ingenieria de software,2,manana unicamente,soacha (al rededores),bus,0-30 min,30-60 min,0,ambos,3,5,1.5,0,3.6 a 4.0,a veces,5.5,no,escuchar musica o podcast,no
36,ingenieria industrial,2,manana y tarde,sibate,bus,61-90 min,30-60 min,0,ambos,5,6,1.5,1,3.6 a 4.0,a veces,3.5,a veces,escuchar musica o podcast,si
37,ciencias del deporte,3,manana y tarde,soacha (central),caminando,0-30 min,0-30 min,0,ambos,2,5,1.5,0,3.6 a 4.0,si,3.5,si,escuchar musica o podcast,si
38,ingenieria de software,1,manana y tarde,sibate cundinamarca,bus,30-60 min,0-30 min,0,ambos,3,3,1.5,0,4.1 a 4.5,a veces,3.5,si,escuchar musica o podcast,tal vez
39,ciencias del deporte,1,manana y tarde,soacha (al rededores),bus,30-60 min,30-60 min,0,ambos,3,5,1.5,1,3.6 a 4.0,a veces,1.0,no,escuchar musica o podcast,no
40,ingenieria de software,4,manana y tarde,soacha (central),caminando,0-30 min,0-30 min,0,ambos,3,4,0.0,0,4.6 a 5,a veces,3.5,no,nada,tal vez
41,ciencias del deporte,2,manana y tarde,soacha (al rededores),moto (combustion o electrica),0-30 min,0-30 min,0,ambos,3,5,0.0,0,3.6 a 4.0,si,3.5,a veces,escuchar musica o podcast,si
42,ingenieria industrial,2,manana y tarde,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,pico,4,4,1.5,1,4.1 a 4.5,a veces,3.5,a veces,nada,tal vez
43,ingenieria de software,4,manana y tarde,bogota (norte),moto (combustion o electrica),30-60 min,30-60 min,0,ambos,5,4,3.5,0,3.6 a 4.0,si,5.5,si,nada,si
44,contaduria publica,1,noche,soacha (central),bus,0-30 min,30-60 min,0,ambos,3,4,1.5,1,3.6 a 4.0,si,3.5,si,escuchar musica o podcast,si
45,ingenieria topografica y geomatica,1,manana y tarde,bogota (centro),"transmilenio (buses troncales, sitp, alimentador)",61-90 min,61-90 min,1,ambos,3,5,3.5,1,3.6 a 4.0,si,3.5,a veces,escuchar musica o podcast,si
46,administracion de empresas,1,noche,soacha (central),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,valle,2,5,0.0,0,4.1 a 4.5,si,5.5,si,escuchar musica o podcast,tal vez
47,ingenieria de software,4,manana y tarde,bogota (sur),"bicicleta, mono patin, patineta, etc.",0-30 min,0-30 min,0,ambos,3,4,1.5,0,4.1 a 4.5,a veces,3.5,a veces,escuchar musica o podcast,tal vez
48,ingenieria industrial,2,manana y tarde,soacha (central),bus,30-60 min,30-60 min,0,ambos,3,4,1.5,1,3.6 a 4.0,a veces,1.0,a veces,usar redes sociales o juegos,tal vez
49,administracion de empresas,1,noche,bogota (norte),"transmilenio (buses troncales, sitp, alimentador)",91-120 min,91-120 min,2,ambos,5,4,5.0,4,3.6 a 4.0,si,1.0,si,escuchar musica o podcast,si

In [30]:
# exportar la data limpia y lista para analisis a csv
df.to_csv("../datos_limpios/Datos_universidad.csv", index=False, encoding="utf-8")